name: Update Freeproxy

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  push:
    branches:
      - main

jobs:
  update_freeproxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 更新到 v4

    - name: Set up Python
      uses: actions/setup-python@v4  # 更新到 v4
      with:
        python-version: '3.x'  # 使用 Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests schedule

    - name: Run update script
      run: python update_freeproxy.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add freeproxy.yml
        git commit -m 'Update freeproxy.yml'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
