name: Fetch File and Publish to GitHub Pages

on:
  schedule:
    # Runs at midnight every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Fetch the file from the URL
    - name: Fetch file from URL
      run: |
        curl -o docs/index.html http://zmm.300000.best

    # Commit and push the file to GitHub Pages
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/index.html
        git commit -m "Update file from zmm.300000.best"
        git push
